title: "Zhuoka Feng"
description: "Personal academic homepage"
url: "https://arkazhuo.github.io"
baseurl: ""
repository: "ArkaZhuo/ArkaZhuo.github.io"

google_scholar_stats_use_cdn: true

author:
  name: "Zhuoka Feng"
  bio: "School of Computer Science, Fudan University"
  email: "23307130211@m.fudan.edu.cn"
  avatar: "images/profile.jpg"
  location: "Shanghai, China"
  github: "ArkaZhuo"

exclude:
  - README.md
  - docs/
